[build]
    publish = "build"
    command = "yarn build"

[context.production.environment]
    REACT_APP_API = "https://api.take.shop"
    REACT_APP_CAPTCHA_KEY="6Ld885UUAAAAAL1-6pc4j_tXsa6ukMlbYqjkYZBl"

[context.deploy-preview.environment]
    REACT_APP_API = "https://staging.api.take.shop"
     REACT_APP_CAPTCHA_KEY="6Ld885UUAAAAAL1-6pc4j_tXsa6ukMlbYqjkYZBl"

[context.branch-deploy.environment]
    REACT_APP_API = "https://staging.api.take.shop"
     REACT_APP_CAPTCHA_KEY="6Ld885UUAAAAAL1-6pc4j_tXsa6ukMlbYqjkYZBl"
