export const Subscriptions = {
    Starter: {
        Price: 0,
        ProductsAmount: 100,
        OrdersAmountMontly: 'Unlimited',
        TakeDropMargin: 0,
        ShopsAmount: 1,
    },
    Basic: {
        Price: 149,
        ProductsAmount: 2500,
        OrdersAmountMontly: 'Unlimited',
        TakeDropMargin: 0,
        ShopsAmount: 3,
    },
    Pro: {
        Price: 499,
        ProductsAmount: 50000,
        OrdersAmountMontly: 'Unlimited',
        TakeDropMargin: 0,
        ShopsAmount: 10,
    },
}

export const Features = {
    'Profesjonalna szata graficzna': [true, true, true],
    'Kody rabatowe': [true, true, true],
    'Ustawienia marży': [true, true, true],
    'Gotowe szablony e-mail': [true, true, true],
    'Integracja z BaseLinker': [true, true, true],
    'Integracja z PayU, PayPal i przelew bankowy': [true, true, true],
    'Pixel facebook oraz eventy': [true, true, true],
    'Eksport feedu produktowego w XML': [true, true, true],
    Sitemap: [true, true, true],
    Regulamin: [true, true, true],
    'Centrum pomocy': [true, true, true],
    'Automatyczna realizacja zamówień': [true, true, true],
    'Certyfikat SSL': [true, true, true],
    'Obsługa ponad 50 języków': [true, true, true],
    'Aktualizacja produktów w AliExpress': [false, true, true],
    'Bezpośredni import produktów z Aliexpress': [false, true, true],
    'Edycja motywu': [false, true, true],
    'Edycja domeny': [false, true, true],
    'Tworzenie artykułów blogowych': [false, true, true],
    'Tryb szalonych zakupów': [false, true, true],
    'TakeStory - relacje użytkowników': [false, true, true],
    'Przypomnienie o nieopłaconym zamówieniu': [false, true, true],
    'Odzyskiwanie porzuconych koszyków': [false, true, true],
    'Zarządzanie użytkownikami': [false, false, true],
    'Sztuczna inteligencja': [false, false, true],
}
